apiVersion: v1
kind: Secret
metadata:
  name: weather-secrets
type: Opaque
data:
  OPENWEATHER_API_KEY: MGYyMWFkOTFjZjE0NzYzNzI5MDBkNGI1NWQxOWQwZGQ=
  DB_USER: d2VhdGhlcl91c2Vy
  DB_PASSWORD: d2VhdGhlcl9wYXNz
  DB_NAME: d2VhdGhlcl9kYg==